//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmellyEggPasswordManager.MyImageWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyImageWebservice.MyWebserviceSoap")]
    public interface MyWebserviceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SmellyEggPasswordManager.MyImageWebservice.HelloWorldResponse HelloWorld(SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.HelloWorldResponse> HelloWorldAsync(SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 fs 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        SmellyEggPasswordManager.MyImageWebservice.UploadFileResponse UploadFile(SmellyEggPasswordManager.MyImageWebservice.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.UploadFileResponse> UploadFileAsync(SmellyEggPasswordManager.MyImageWebservice.UploadFileRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 listfilenames 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFiles", ReplyAction="*")]
        SmellyEggPasswordManager.MyImageWebservice.DeleteFilesResponse DeleteFiles(SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteFiles", ReplyAction="*")]
        System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.DeleteFilesResponse> DeleteFilesAsync(SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmellyEggPasswordManager.MyImageWebservice.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SmellyEggPasswordManager.MyImageWebservice.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public SmellyEggPasswordManager.MyImageWebservice.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(SmellyEggPasswordManager.MyImageWebservice.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] fs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileName;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(byte[] fs, string fileName) {
            this.fs = fs;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmellyEggPasswordManager.MyImageWebservice.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(SmellyEggPasswordManager.MyImageWebservice.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(string UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFiles", Namespace="http://tempuri.org/", Order=0)]
        public SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequestBody Body;
        
        public DeleteFilesRequest() {
        }
        
        public DeleteFilesRequest(SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SmellyEggPasswordManager.MyImageWebservice.ArrayOfString listfilenames;
        
        public DeleteFilesRequestBody() {
        }
        
        public DeleteFilesRequestBody(SmellyEggPasswordManager.MyImageWebservice.ArrayOfString listfilenames) {
            this.listfilenames = listfilenames;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmellyEggPasswordManager.MyImageWebservice.DeleteFilesResponseBody Body;
        
        public DeleteFilesResponse() {
        }
        
        public DeleteFilesResponse(SmellyEggPasswordManager.MyImageWebservice.DeleteFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteFilesResult;
        
        public DeleteFilesResponseBody() {
        }
        
        public DeleteFilesResponseBody(bool DeleteFilesResult) {
            this.DeleteFilesResult = DeleteFilesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebserviceSoapChannel : SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebserviceSoapClient : System.ServiceModel.ClientBase<SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap>, SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap {
        
        public MyWebserviceSoapClient() {
        }
        
        public MyWebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmellyEggPasswordManager.MyImageWebservice.HelloWorldResponse SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap.HelloWorld(SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequest inValue = new SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequest();
            inValue.Body = new SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequestBody();
            SmellyEggPasswordManager.MyImageWebservice.HelloWorldResponse retVal = ((SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.HelloWorldResponse> SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap.HelloWorldAsync(SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.HelloWorldResponse> HelloWorldAsync() {
            SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequest inValue = new SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequest();
            inValue.Body = new SmellyEggPasswordManager.MyImageWebservice.HelloWorldRequestBody();
            return ((SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmellyEggPasswordManager.MyImageWebservice.UploadFileResponse SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap.UploadFile(SmellyEggPasswordManager.MyImageWebservice.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public string UploadFile(byte[] fs, string fileName) {
            SmellyEggPasswordManager.MyImageWebservice.UploadFileRequest inValue = new SmellyEggPasswordManager.MyImageWebservice.UploadFileRequest();
            inValue.Body = new SmellyEggPasswordManager.MyImageWebservice.UploadFileRequestBody();
            inValue.Body.fs = fs;
            inValue.Body.fileName = fileName;
            SmellyEggPasswordManager.MyImageWebservice.UploadFileResponse retVal = ((SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.UploadFileResponse> SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap.UploadFileAsync(SmellyEggPasswordManager.MyImageWebservice.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.UploadFileResponse> UploadFileAsync(byte[] fs, string fileName) {
            SmellyEggPasswordManager.MyImageWebservice.UploadFileRequest inValue = new SmellyEggPasswordManager.MyImageWebservice.UploadFileRequest();
            inValue.Body = new SmellyEggPasswordManager.MyImageWebservice.UploadFileRequestBody();
            inValue.Body.fs = fs;
            inValue.Body.fileName = fileName;
            return ((SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap)(this)).UploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmellyEggPasswordManager.MyImageWebservice.DeleteFilesResponse SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap.DeleteFiles(SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequest request) {
            return base.Channel.DeleteFiles(request);
        }
        
        public bool DeleteFiles(SmellyEggPasswordManager.MyImageWebservice.ArrayOfString listfilenames) {
            SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequest inValue = new SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequest();
            inValue.Body = new SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequestBody();
            inValue.Body.listfilenames = listfilenames;
            SmellyEggPasswordManager.MyImageWebservice.DeleteFilesResponse retVal = ((SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap)(this)).DeleteFiles(inValue);
            return retVal.Body.DeleteFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.DeleteFilesResponse> SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap.DeleteFilesAsync(SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequest request) {
            return base.Channel.DeleteFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmellyEggPasswordManager.MyImageWebservice.DeleteFilesResponse> DeleteFilesAsync(SmellyEggPasswordManager.MyImageWebservice.ArrayOfString listfilenames) {
            SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequest inValue = new SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequest();
            inValue.Body = new SmellyEggPasswordManager.MyImageWebservice.DeleteFilesRequestBody();
            inValue.Body.listfilenames = listfilenames;
            return ((SmellyEggPasswordManager.MyImageWebservice.MyWebserviceSoap)(this)).DeleteFilesAsync(inValue);
        }
    }
}
